package com.vyatsu.practiceCSR.logger;

public enum EnumWarnLog {
    CREATE_USER,
    CREATE_SERVICE,
    CREATE_REPORT,
    COPY_REPORT,
    CREATE_TEMPLATE,
    UPDATE_TEMPLATE,
    UPDATE_USER,
    SAVE_REPORT,
    COMPLETE_REPORT,
    COMPLETE_TIMEOUT_REPORT,
    DROP_USER,
    DROP_SERVICE,
    DROP_TEMPLATE,

    AUTH_USER,
    VIEW_USER_REPORT,
    GENERATE_SUMMARY_REPORT,

    BAD_AUTH_USER
}
